config/routes.rb
Rails.application.routes.draw do

  root to: "restaurants#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  has_many :reviews,
      -> { extending WithUserAssociationExtension },
      dependent: :destroy
  validates :name, length:{minimum:3}, uniqueness: true

  # def average_rating
  #   return 'N/A' if reviews.none?
  #   puts reviews.count
  #   reviews.inject(0) {|memo, review| memo + review.rating}/reviews.count
  # end

  def average_rating
    reviews.average(:rating)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :rating, inclusion: (1..5)
  belongs_to :restaurant
  belongs_to :user
  has_many :endorsements
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }


  def get_email(user_id)
    user = User.find(user_id)
    user.email
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

 def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    # user.name = auth.info.name   # assuming the user model has a name
    # user.image = auth.info.image # assuming the user model has an image
  end
 end

 def has_reviewed?(restaurant)
   reviewed_restaurants.include? restaurant
 end

 def owns?(entity)
   entity.user_id == self.id
 end




 # def review_id_finder(restaurant)
 # end

end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: @review.endorsements.count}
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]
  before_action :restaurant_owner, :except =>[:index, :show, :new, :create]


  def restaurant_owner
    @restaurant = Restaurant.find(params[:id])
    unless @restaurant.user_id == current_user.id
      flash[:notice] = 'You are not authorised to change the restaurant'
      redirect_to restaurants_path
    end
  end


  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to '/restaurants'
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :image)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

end

# migration for join table:
# bin/rails d migration CreateJoinTableReviewedRestaurants user restaurant review

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user! #, :except => [:index, :show]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.create_with_user review_params, current_user
    redirect_to restaurants_path
  end


  def destroy
    @review = Review.find(params[:id])
    if (@review.user_id == current_user.id)
      @review.destroy
      flash[:notice] = 'Review deleted successfully'
    end
    redirect_to '/restaurants'
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end




  # def only_one_review_checker
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  #   if (@restaurant.reviews.find_by(user_id: current_user.id)) != nil
  #     flash[:notice] = 'You can only review a restaurant once'
  #     redirect_to restaurants_path and return 'stop'
  #   end
  # end
  #
  #
  # def create
  #   return if only_one_review_checker == 'stop'
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  #   @restaurant.reviews.create(review_params)
  #
  #   redirect_to restaurants_path and return
  # end




end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5-rating)
    "★" * rating.round + "☆" * remainder
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title YelpClone
    %meta(charset="UTF-8")
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/restaurants/_form.html.haml
= form_for @restaurant, html: {multipart: true} do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_field :description
  = f.label :image
  = f.file_field :image
  = f.submit

app/views/restaurants/edit.html.haml
= render "form"

app/views/restaurants/index.html.haml
- if user_signed_in?
  = link_to "Sign out", destroy_user_session_path, method: :delete
- else
  = link_to "Sign up", new_user_registration_path
  = link_to "Sign in", new_user_session_path


- if @restaurants.any?
  - @restaurants.each do |restaurant|
    %h2= link_to restaurant.name, restaurant_path(restaurant)
    = image_tag restaurant.image.url(:thumb)
    %h3 Reviews:
    - if restaurant.reviews.any?
      %ul
      - restaurant.reviews.each do |review|
        %li
          = review.thoughts
          %strong= review.rating
          \/5 by:
          = review.get_email(review.user_id)
          = distance_of_time_in_words(Time.at(review.created_at), Time.now)
          = link_to "Endorse", review_endorsements_path(review), class: 'endorsements-link'
          %span.endorsements_count= review.endorsements.count
          = 'endorsement'.pluralize review.endorsements.count
          - if (current_user && current_user.owns?(review) )
            = link_to "Delete review", review_path(review), method: :delete
      %h3 Average rating: #{star_rating(restaurant.average_rating)}
    - else
      %p No reviews
    - if (current_user && current_user.has_reviewed?(restaurant))
      %p You have already reviewed: <b>#{restaurant.name}</b>
    - elsif (current_user && current_user.owns?(restaurant))
      %p You cannot review a restaurant you added
    - else
      = link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
    = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
    = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
- else
  %h1 No restaurant yet!

%a(href=new_restaurant_path) Add a restaurant

app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize @restaurant.errors.count, "error"
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message

= render "form"

app/views/reviews/new.html.haml
= form_for [@restaurant,@review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'